# Generated by Django 5.2.13 on 2026-08-25 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='Asignación automática activada')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ultimo_asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Último asesor asignado (turno round-robin)')),
            ],
            options={
                'verbose_name': 'Configuración de asignación automática',
                'verbose_name_plural': 'Configuración de asignación automática',
            },
        ),
    ]
