# Generated by Django 5.2.13 on 2026-08-25 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('texto', models.CharField(max_length=255)),
                ('completada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_agenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha'], name='agenda_tare_usuario_8a7293_idx')],
            },
        ),
    ]
