# Generated by Django 5.2.13 on 2026-04-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('interes', models.CharField(choices=[('seguro_vida', 'Seguro de vida'), ('medico', 'Gastos médicos'), ('auto', 'Seguro de auto'), ('hogar', 'Seguro de hogar'), ('inversion', 'Inversión y ahorro'), ('empresa', 'Empresarial'), ('general', 'Información general')], max_length=30)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('convertido', 'Convertido en cliente'), ('descartado', 'Descartado')], default='nuevo', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_contacto', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('asesor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'ordering': ['-fecha'],
            },
        ),
    ]
