# Generated by Django 5.2.13 on 2026-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('personal', 'Seguros Personales'), ('inversion', 'Ahorro e Inversion'), ('empresarial', 'Empresarial')], max_length=30)),
                ('descripcion', models.TextField()),
                ('descripcion_corta', models.CharField(max_length=300)),
                ('icono_clase', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
    ]
