# Generated by Django 5.2.13 on 2026-08-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('personal', 'Seguros Personales'), ('inversion', 'Ahorro e Inversión'), ('empresarial', 'Empresarial')], max_length=30),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
