# Generated by Django 5.2.13 on 2026-08-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_categoria_alter_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='icono_clase',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
