# Generated by Django 5.2.13 on 2026-05-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('asesor', 'Asesor')], default='asesor', max_length=10),
        ),
    ]
