"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ─────────────────────────────────────────────
# FASE D (punto 15-16): SECRET_KEY, DEBUG, ALLOWED_HOSTS y las credenciales
# de la base de datos ya NO están escritos aquí en texto plano. Se leen del
# archivo `.env` (ignorado por git, ver .gitignore) mediante python-decouple.
#
# Si `.env` no existe todavía, `config()` usa el valor por default indicado
# abajo (el mismo que ya traía el proyecto), así que no se rompe nada en
# desarrollo aunque falte crear el archivo. Ver `.env.example` para la
# plantilla de qué variables definir.
# ─────────────────────────────────────────────

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-bjr9f01^!29_h_#4x-9c2y%=d5$3&jzh2!mnsnu2w*gwx*dv=5',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# ─────────────────────────────────────────────
# Render asigna el dominio *.onrender.com y lo expone en esta variable
# de entorno automáticamente (no hay que configurarla a mano). Si existe,
# se agrega sola a ALLOWED_HOSTS y CSRF_TRUSTED_ORIGINS.
# ─────────────────────────────────────────────
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# ─────────────────────────────────────────────
# Ruta del panel de administración: no se deja fija en 'admin/' porque
# es la primera ruta que prueban los bots que escanean sitios Django
# buscando el login del admin. Se define en .env (nunca en el código,
# para que no quede visible en el historial de GitHub). Si no está
# definida, cae a un default distinto del estándar.
# ─────────────────────────────────────────────
ADMIN_URL = config('ADMIN_URL', default='panel-vr-gestion/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'citas',
    'postulantes',
    'vacantes',
    'servicios',
    'usuarios',
    'dashboard',
    'historial',
    'prospectos',
    'inicio',
    'reportes',
    'agenda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.tz',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='vr_consultores'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Archivos estáticos (CSS, JS, imágenes)
STATICFILES_DIRS = [BASE_DIR / 'static']

# ─────────────────────────────────────────────
# LOGIN / AUTENTICACIÓN
# ─────────────────────────────────────────────
LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/usuarios/login/'

# ─────────────────────────────────────────────
# SESIONES Y CSRF (FASE D — punto 7)
# ─────────────────────────────────────────────
# DESARROLLO (HTTP local): las cookies *_SECURE deben quedar en False,
# porque exigir HTTPS aquí rompería el login en `runserver` (127.0.0.1
# sirve por HTTP). HTTPONLY y SAMESITE sí se pueden activar sin romper
# nada, y ya dan protección real contra robo de cookie vía JavaScript
# (XSS) y contra CSRF entre sitios.
SESSION_COOKIE_HTTPONLY = True          # la cookie de sesión no es legible desde JS
SESSION_COOKIE_SAMESITE = 'Lax'         # no se envía en peticiones cross-site
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # la sesión termina al cerrar el navegador

# PRODUCCIÓN (DEBUG=False, HTTPS de Render): las cookies *_SECURE y las
# cabeceras HSTS se activan solas, sin tener que acordarte de cambiar nada
# a mano en cada deploy. En desarrollo (DEBUG=True, runserver por HTTP)
# se quedan desactivadas para no romper el login local.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# ─────────────────────────────────────────────
# ARCHIVOS ESTÁTICOS (para producción)
# ─────────────────────────────────────────────
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ─────────────────────────────────────────────
# Almacenamiento de archivos:
# - Estáticos (CSS/JS del proyecto) → WhiteNoise, sirven desde el propio
#   servidor de Render, no cambian con cada deploy.
# - Media (CVs, fotos de servicios, fotos de perfil, pólizas subidas por
#   usuarios) → Cloudinary, porque el disco de Render en el plan Free NO
#   es persistente: cualquier archivo subido por un usuario se perdería
#   en el siguiente deploy o reinicio si se quedara solo en el servidor.
# Si faltan las credenciales de Cloudinary (ej. en tu máquina local sin
# .env configurado para esto), cae de vuelta al disco local para que
# sigas pudiendo trabajar en desarrollo sin necesidad de una cuenta.
# ─────────────────────────────────────────────
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

if CLOUDINARY_STORAGE['CLOUD_NAME']:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# ─────────────────────────────────────────────
# CORREO ELECTRÓNICO (para recuperación de contraseña)
# ─────────────────────────────────────────────
# Envío real vía Gmail SMTP. El usuario y la contraseña de aplicación se
# leen desde .env (nunca escritos aquí en texto plano). Si EMAIL_HOST_USER
# o EMAIL_HOST_PASSWORD no están definidos en .env, se cae automáticamente
# al backend de consola (imprime el correo en la terminal) para no romper
# el flujo de pruebas si alguien clona el proyecto sin credenciales.
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = f'Grupo V&R <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'Grupo V&R <no-responder@grupovr.local>'

# Archivos subidos por usuarios (CVs, imágenes, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'