# Generated by Django 5.2.13 on 2026-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('modalidad', models.CharField(choices=[('completo', 'Tiempo completo'), ('medio', 'Medio Timepo'), ('remoto', 'Remoto')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-creada'],
            },
        ),
    ]
