# Generated by Django 5.2.13 on 2026-05-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='actualizada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='activa', max_length=10),
        ),
        migrations.AddField(
            model_name='vacante',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de postulación'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vacantes/imagenes/', verbose_name='Imagen de portada'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='pdf_convocatoria',
            field=models.FileField(blank=True, null=True, upload_to='vacantes/pdfs/', verbose_name='PDF de convocatoria'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='requisitos',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='sueldo',
            field=models.CharField(blank=True, help_text='Ej: $8,000 – $12,000 MXN mensual', max_length=100, null=True, verbose_name='Sueldo / Rango salarial'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Área / Departamento'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del puesto'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='modalidad',
            field=models.CharField(choices=[('completo', 'Tiempo completo'), ('medio', 'Medio tiempo'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='completo', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del puesto'),
        ),
    ]
