# Generated by Django 5.2.13 on 2026-04-24 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('revision', 'Revision'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vacante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulantes', to='vacantes.vacante')),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'ordering': ['-fecha'],
            },
        ),
    ]
