# Generated by Django 5.2.13 on 2026-05-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('revisado', 'Revisado'), ('entrevista', 'Entrevista'), ('finalista', 'Finalista'), ('contratado', 'Contratado'), ('rechazado', 'Rechazado')], default='nuevo', max_length=20),
        ),
    ]
