# Generated by Django 5.2.13 on 2026-05-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0002_alter_postulante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones privadas del reclutador. No visibles para el postulante.', null=True, verbose_name='Notas internas'),
        ),
    ]
