# Generated by Django 5.2.13 on 2026-08-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0003_postulante_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='fecha_entrevista',
            field=models.DateTimeField(blank=True, help_text='Se captura al marcar al postulante como "Entrevista".', null=True, verbose_name='Fecha y hora de entrevista'),
        ),
    ]
