# Generated by Django 5.2.13 on 2026-04-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=300)),
                ('modulo', models.CharField(choices=[('citas', 'Citas'), ('postulantes', 'Postulantes'), ('vacantes', 'Vacantes'), ('servicios', 'Servicios'), ('usuarios', 'Usuarios'), ('prospectos', 'Prospectos'), ('dashboard', 'Dashboard')], max_length=20)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial de actividad',
                'ordering': ['-fecha'],
            },
        ),
    ]
