# Generated by Django 5.2.13 on 2026-08-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_alter_historial_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='modulo',
            field=models.CharField(choices=[('citas', 'Citas'), ('postulantes', 'Postulantes'), ('vacantes', 'Vacantes'), ('usuarios', 'Usuarios'), ('prospectos', 'Prospectos'), ('dashboard', 'Dashboard'), ('agenda', 'Agenda')], max_length=20),
        ),
    ]